name: 测试自动打包和部署

on:
  push:
    branches:
      - main  # 指定触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload to Pgyer
        uses: xtayga/upload-pgyer-action@master
        with:
          url: https://www.pgyer.com/apiv2/app/upload
          forms: '{"_api_key":"${{ secrets.PGYER_API_KEY }}","buildName":"YourAppName"}'
          fileForms: '{"file":"build/app/outputs/flutter-apk/app-release.apk"}'
